# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  orderer2.example.com:
  orderer3.example.com:
  orderer4.example.com:
  peer0.org1.example.com:
  peer0.org2.example.com:

networks:
  test:

services:

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BCCSP_DEFAULT=PKCS11
      - ORDERER_GENERAL_BCCSP_PKCS11_LIBRARY=/usr/local/lib/softhsm/libsofthsm2.so
      - ORDERER_GENERAL_BCCSP_PKCS11_PIN=71811222
      - ORDERER_GENERAL_BCCSP_PKCS11_LABEL=fabric
      - ORDERER_GENERAL_BCCSP_PKCS11_FILEKEYSTORE_KEYSTORE=/signcerts
      - ORDERER_GENERAL_BCCSP_PKCS11_FILE_KEY_STORE_KEY_STORE=/signcerts
      - SOFTHSM2_CONF=/etc/softhsm2.conf
      - FABRIC_LOGGING_SPEC=debug
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: sh -c '/entrypoint.sh'
    volumes:
        - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example.com:/var/hyperledger/production/orderer
        - ../organizations:/organizations
        - ../scripts/entry-points/orderer.sh:/entrypoint.sh
    ports:
      - 7050:7050
    networks:
      - test


  orderer2.example.com:
    container_name: orderer2.example.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=10050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BCCSP_DEFAULT=PKCS11
      - ORDERER_GENERAL_BCCSP_PKCS11_LIBRARY=/usr/local/lib/softhsm/libsofthsm2.so
      - ORDERER_GENERAL_BCCSP_PKCS11_PIN=71811222
      - ORDERER_GENERAL_BCCSP_PKCS11_LABEL=fabric
      - ORDERER_GENERAL_BCCSP_PKCS11_FILEKEYSTORE_KEYSTORE=/signcerts
      - ORDERER_GENERAL_BCCSP_PKCS11_FILE_KEY_STORE_KEY_STORE=/signcerts
      - SOFTHSM2_CONF=/etc/softhsm2.conf
      - FABRIC_LOGGING_SPEC=debug
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: sh -c '/entrypoint.sh'
    volumes:
        - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/msp:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer2.example.com:/var/hyperledger/production/orderer
        - ../organizations:/organizations
        - ../scripts/entry-points/orderer2.sh:/entrypoint.sh
    ports:
      - 10050:10050
    networks:
      - test


  orderer3.example.com:
    container_name: orderer3.example.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=11050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BCCSP_DEFAULT=PKCS11
      - ORDERER_GENERAL_BCCSP_PKCS11_LIBRARY=/usr/local/lib/softhsm/libsofthsm2.so
      - ORDERER_GENERAL_BCCSP_PKCS11_PIN=71811222
      - ORDERER_GENERAL_BCCSP_PKCS11_LABEL=fabric
      - ORDERER_GENERAL_BCCSP_PKCS11_FILEKEYSTORE_KEYSTORE=/signcerts
      - ORDERER_GENERAL_BCCSP_PKCS11_FILE_KEY_STORE_KEY_STORE=/signcerts
      - SOFTHSM2_CONF=/etc/softhsm2.conf
      - FABRIC_LOGGING_SPEC=debug
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: sh -c '/entrypoint.sh'
    volumes:
        - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../organizations/ordererOrganizations/example.com/orderers/orderer3.example.com/msp:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer3.example.com:/var/hyperledger/production/orderer
        - ../organizations:/organizations
        - ../scripts/entry-points/orderer3.sh:/entrypoint.sh
    ports:
      - 11050:11050
    networks:
      - test

  # orderer4.example.com:
  #   container_name: orderer4.example.com
  #   image: hyperledger/fabric-orderer:$IMAGE_TAG
  #   environment:
  #     - FABRIC_LOGGING_SPEC=INFO
  #     - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
  #     - ORDERER_GENERAL_LISTENPORT=12050
  #     - ORDERER_GENERAL_GENESISMETHOD=file
  #     - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
  #     - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
  #     - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
  #     # enabled TLS
  #     - ORDERER_GENERAL_TLS_ENABLED=true
  #     - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
  #     - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
  #     - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
  #     - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
  #     - ORDERER_KAFKA_VERBOSE=true
  #     - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
  #     - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
  #     - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
  #     - ORDERER_GENERAL_BCCSP_DEFAULT=PKCS11
  #     - ORDERER_GENERAL_BCCSP_PKCS11_LIBRARY=/usr/local/lib/softhsm/libsofthsm2.so
  #     - ORDERER_GENERAL_BCCSP_PKCS11_PIN=71811222
  #     - ORDERER_GENERAL_BCCSP_PKCS11_LABEL=fabric
  #     - ORDERER_GENERAL_BCCSP_PKCS11_FILEKEYSTORE_KEYSTORE=/signcerts
  #     - ORDERER_GENERAL_BCCSP_PKCS11_FILE_KEY_STORE_KEY_STORE=/signcerts
  #     - SOFTHSM2_CONF=/etc/softhsm2.conf
  #     - FABRIC_LOGGING_SPEC=debug
  #   working_dir: /opt/gopath/src/github.com/hyperledger/fabric
  #   command: sh -c '/entrypoint.sh'
  #   volumes:
  #       - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
  #       - ../organizations/ordererOrganizations/example.com/orderers/orderer4.example.com/msp:/var/hyperledger/orderer/msp
  #       - ../organizations/ordererOrganizations/example.com/orderers/orderer4.example.com/tls/:/var/hyperledger/orderer/tls
  #       - orderer4.example.com:/var/hyperledger/production/orderer
  #       - ../organizations:/organizations
  #       - ../scripts/entry-points/orderer4.sh:/entrypoint.sh
  #   ports:
  #     - 12050:12050
  #   networks:
  #     - test


  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_LIMITS_CONCURRENCY_ENDORSERSERVICE=0
      - CORE_PEER_LIMITS_CONCURRENCY_ENDORSER_SERVICE=0
      - CORE_PEER_LIMITS_CONCURRENCY_DELIVERSERVICE=0
      - CORE_PEER_LIMITS_CONCURRENCY_DELIVER_SERVICE=0
      - CORE_PEER_BCCSP_DEFAULT=PKCS11
      - CORE_PEER_BCCSP_PKCS11_LIBRARY=/usr/local/lib/softhsm/libsofthsm2.so
      - CORE_PEER_BCCSP_PKCS11_PIN=71811222
      - CORE_PEER_BCCSP_PKCS11_LABEL=fabric
      - SOFTHSM2_CONF=/etc/softhsm2.conf
      - FABRIC_LOGGING_SPEC=debug
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
        - ../organizations:/organizations
        - ../scripts/entry-points/peer0org1.sh:/entrypoint.sh
        - peer0.org1.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: sh -c '/entrypoint.sh'
    ports:
      - 7051:7051
    networks:
      - test

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_ADDRESS=peer0.org2.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_LIMITS_CONCURRENCY_ENDORSERSERVICE=0
      - CORE_PEER_LIMITS_CONCURRENCY_ENDORSER_SERVICE=0
      - CORE_PEER_LIMITS_CONCURRENCY_DELIVERSERVICE=0
      - CORE_PEER_LIMITS_CONCURRENCY_DELIVER_SERVICE=0
      - CORE_PEER_BCCSP_DEFAULT=PKCS11
      - CORE_PEER_BCCSP_PKCS11_LIBRARY=/usr/local/lib/softhsm/libsofthsm2.so
      - CORE_PEER_BCCSP_PKCS11_PIN=71811222
      - CORE_PEER_BCCSP_PKCS11_LABEL=fabric
      - SOFTHSM2_CONF=/etc/softhsm2.conf
      - FABRIC_LOGGING_SPEC=debug
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.example.com:/var/hyperledger/production
        - ../organizations:/organizations
        - ../scripts/entry-points/peer0org2.sh:/entrypoint.sh
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: sh -c '/entrypoint.sh'
    ports:
      - 9051:9051
    networks:
      - test
